[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

# ⚠️ Laisser passer les fonctions AVANT la règle SPA
[[redirects]]
  from = "/.netlify/functions/*"
  to   = "/.netlify/functions/:splat"
  status = 200

# SPA fallback (Vite)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
