[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

# Optional: make sure /admin also serves the SPA entry
[[redirects]]
  from = "/admin"
  to   = "/index.html"
  status = 200

# SPA fallback for all other frontend routes
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
